name: Lab2 CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      working-directory: lab2
      run: yarn install --non-interactive --no-progress --skip-integrity-check --frozen-lockfile
    - name: Run tests
      working-directory: lab2
      run: |
        yarn start
        echo "==================== OK ===================="
        cat ok.txt
        echo "==================== ERROR ===================="
        cat err.txt
      env:
        CI: true
